### ISSUE TITLE
High level analysis does not show any data sources

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/Team_Team6_CS-GY-6063-Fall2021#17]
Please include data sources and an epic how the data gets into the system

**Comment by sballan** [comment]
@gcivil-nyu Hi professor, we're working on this now.

We've decided to use online data from Yelp instead of importing OpenNYC data to our database.  In this case, there is no independent "Data Import Process"; rather, data is "lazily loaded" into our database as our users request it.  I've described the details [here](https://github.com/gcivil-nyu-org/Team_Team6_CS-GY-6063-Fall2021/wiki/High-Level-Analysis#dayplanner-application---yelp-integration).

Does this seem alright?  Thanks!
